languageCode = "en-us"

baseURL             = "http://homeonrails.com"
copyright           = "All rights reserved - 2017"
paginate            = 5
pluralizeListTitles = false
theme               = "casper"
title               = "Home on Rails"

disqusshortname = "homeonrails"
pygmentsStyle   = "monokai"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/"
  weight     = -120

[[menu.main]]
  name   = "Github repos"
  pre    = "<h3>Follow me</h3>"
  url    = "https://github.com/akalyaev"
  weight = 100

[[menu.main]]
  name   = "Twitter timeline"
  url    = "https://twitter.com/AntonKalyaev"
  weight = 101

[params]
  author                = "Anton Kalyaev"
  authorlocation        = "Ulyanovsk, Russia"
  authorwebsite         = "http://homeonrails.com"
  bio                   = "Software engineer, blogger, public speaker, traveler"
  cover                 = "images/cover.png"
  description           = "Notes on software development, travels and life"
  githubName            = "akalyaev"
  googleAnalyticsUserID = "UA-35080566-1"
  hideHUGOSupport       = false
  logo                  = "images/logo.png"
  twitterName           = "AntonKalyaev"

[sitemap]
  ChangeFreq = ""
  Filename   = "sitemap.xml"
  Priority   = "-1"
